# Replit configuration for auto-sync with GitHub
language = "nodejs"

[deployment]
run = ["npm", "run", "dev"]
deploymentTarget = "gce"

[packager]
language = "nodejs"

[packager.features]
packageSearch = true
guessImports = true
enabledForHosting = false

[languages.javascript]
pattern = "**/{*.js,*.jsx,*.ts,*.tsx}"

[languages.javascript.languageServer]
start = "typescript-language-server --stdio"

[env]
PATH = "/home/runner/$REPL_SLUG/.config/npm/node_global/bin:/home/runner/$REPL_SLUG/node_modules/.bin"
npm_config_prefix = "/home/runner/$REPL_SLUG/.config/npm/node_global"

[gitHubImport]
requiredFiles = [".replit", "replit.nix", ".config"]

[nix]
channel = "stable-22_11"

[workflows]
runButton = "Project"

[[workflows.workflow]]
name = "Project"
author = "agent"

[[workflows.workflow.tasks]]
task = "shell.exec"
args = "npm run dev"

[deployment]
publicDir = "/"
deploymentTarget = "static"